### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by AIisCool** [claudiom4sir/SuperResolutionOfCompressedVideos#1]
`python test_aim_challenge.py --data_path "C:/AIM2022SuperResolutionOfCompressedVideos/input/Set8/"`

```
C:\AIM2022SuperResolutionOfCompressedVideos>python test_aim_challenge.py --data_path "C:/AIM2022SuperResolutionOfCompressedVideos/input/Set8/"
> Loading pretrained model from best.pth
> Loading video sequences...
Traceback (most recent call last):
  File "C:\AIM2022SuperResolutionOfCompressedVideos\test_aim_challenge.py", line 75, in <module>
    main(args.data_path, args.save_all)
  File "C:\AIM2022SuperResolutionOfCompressedVideos\test_aim_challenge.py", line 32, in main
    testset = AIMChallengeTestset(path_compressed_test)
  File "C:\AIM2022SuperResolutionOfCompressedVideos\dataset.py", line 63, in __init__
    frames = os.listdir(compressed_path)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:/AIM2022SuperResolutionOfCompressedVideos/input/Set8/00000000.png'
```

**Comment by claudiom4sir** [comment]
Hello,

I assumed the dataset is in this way: root, the root contains folders (name of the sequence), each folder contains ordered .png files (representing frames).
Looking at your error, try to write just "C:/AIM2022SuperResolutionOfCompressedVideos/input/", since "Set8" is seen as the sequence name.

Hope this fix your problem.

Claudio

**Comment by AIisCool** [comment]
Thanks for the response! Yes, I have PNG format frames (named "00000000.png" etc) in the Set8 folder. But trying your solution above, I no longer get the "NotADirectoryError" now I get:

```
C:\AIM2022SuperResolutionOfCompressedVideos>python test_aim_challenge.py --data_path "C:/AIM2022SuperResolutionOfCompressedVideos/input/"
> Loading pretrained model from best.pth
> Loading video sequences...
Traceback (most recent call last):
  File "C:\AIM2022SuperResolutionOfCompressedVideos\test_aim_challenge.py", line 75, in <module>
    main(args.data_path, args.save_all)
  File "C:\AIM2022SuperResolutionOfCompressedVideos\test_aim_challenge.py", line 32, in main
    testset = AIMChallengeTestset(path_compressed_test)
  File "C:\AIM2022SuperResolutionOfCompressedVideos\dataset.py", line 69, in __init__
    if int(video) not in self.data.keys():
ValueError: invalid literal for int() with base 10: 'Set8'
```

**Comment by claudiom4sir** [comment]
Ok, it's because the dataset I used had numbers as sequence names, like "001", "002" and so on. You got that error because you're trying to convert "Set8" to an integer. If you rename your sequence name in this way, it should work. Otherwise, you have to remove the int cast on the video variable in dataset.py (line 69 to 73).

**Comment by AIisCool** [comment]
Tried renaming to the same sequence, same issue. Deleted line 69-73. After deleting, ran it again, got:
```
python test_aim_challenge.py --data_path "C:/AIM2022SuperResolutionOfCompressedVideos/input/"
Loading pretrained model from best.pth
Loading video sequences...
Done.
Start testing the model...
0it [00:01, ?it/s]
```

Nothing was processed?

**Comment by claudiom4sir** [comment]
Have you renamed "Set8" in "001"? It's very strange it doesn't work. This error ```ValueError: invalid literal for int() with base 10: 'Set8'``` is given by wrong cast to int, because you cannot cast "Set8" to an integer.

Yes, if you remove those lines the dataset won't be loaded. Try just to remove the ```int``` cast to the ```video``` variable, from ```int(video)``` to ```video``` in those lines.

**Comment by AIisCool** [comment]
Yes, renamed them:
![image](https://user-images.githubusercontent.com/92149242/195001619-47f33452-d8b1-4a59-9675-47bc39475113.png)


Ok so I edited those lines to:
```
                if video not in self.data.keys():
                    self.data[video] = []
                self.data[video].append(video + '/' + frame)
            for indices in generate_indices(len(self.data[video]), temp_size, temp_stride):
                self.indices.append([video, indices])
```

And it ran!

However, the results are just larger, no restoration? I'm not noticing a difference in quality?

**Comment by claudiom4sir** [comment]
Happy that it finally works!

The method is trained for super-resolution of HEVC compressed videos (QP 37). If you don't notice any difference in quality, I believe that the dataset you're using is quite different from the one of the challenge (maybe, different QP, different codec, or it contains too different scenarios). 

The method should improve your PSNR by about 0.4dB.

**Comment by AIisCool** [comment]
> The method is trained for super-resolution of HEVC compressed videos (QP 37). If you don't notice any difference in quality, I believe that the dataset you're using is quite different from the one of the challenge (maybe, different QP, different codec, or it contains too different scenarios).

Maybe it is too different? I had used frames from a DVD with MPEG-2 compression artifacts.

**Comment by claudiom4sir** [comment]
Yes, I think that's the reason why you don't obtain any quality improvement.
